#!/bin/bash
###############################################################################
# Copyright © 2016 Stéphane Veyret stephane_DOT_veyret_AT_neptura_DOT_org
#
# This file is part of kema.
#
# kema is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# kema is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# kema.  If not, see <http://www.gnu.org/licenses/>.
###############################################################################

###############################################################################
# kema, the Gentoo kernel manager.
# Version: 0.3
###############################################################################

# Load configuration
: ${KEMA_CONFIG_DIR:=/etc/kema}
: ${KEMA_CONFIG_FILE:="${KEMA_CONFIG_DIR}/kema.conf"}
[[ -r "${KEMA_CONFIG_FILE}" ]] && . "${KEMA_CONFIG_FILE}"
. gettext.sh

# Kema variables
: ${KEMA_INITRAMFS_OPTS:=}
: ${KEMA_KERNEL_OPTS:=}
: ${KEMA_MAKE_OPTS:="-j4"}
: ${KEMA_PATCH_DIR:="${KEMA_CONFIG_DIR}/patch"}
: ${KEMA_BOOTLOADER:=}
: ${KEMA_INITRAMFS_EMBED:="-"}
: ${KEMA_GENKERNEL_OPTS:=}
: ${KEMA_CORE_DIR:=/usr/libexec/kema}
: ${KEMA_BOOTLOADER_DIR:="${KEMA_CORE_DIR}/bootloader"}
: ${KEMA_VAR_DIR:=/var/lib/kema}
: ${KEMA_SAVED_CONFIG:="${KEMA_VAR_DIR}/saved.config"}
: ${KEMA_ARCH:="${HOSTTYPE}"}

export TEXTDOMAIN=kema

KRED="\e[0;91m"
KGREEN="\e[0;92m"
KYELLOW="\e[0;93m"
KNORMAL="\e[0m"

# Functions to display messages
function einfo
{
  echo -e "${KGREEN}$@${KNORMAL}"
}
function ewarn
{
  echo -e "${KYELLOW}$@${KNORMAL}"
}
function eerror
{
  echo -e "${KRED}$@${KNORMAL}" >&2
  exit 1
}
function ehelp
{
  echo -e "${KRED}$@${KNORMAL}" >&2
  echo -e $(eval_gettext "You may try")
  echo -e "${KGREEN}  kema help${KNORMAL}"
  echo -e $(eval_gettext "to get more information")
  exit 1
}
function pause
{
  echo -e $(eval_gettext "Hit \"Enter\" to continue or Ctrl-C to stop now")
  read
}

# Test if a test is pending
function isTestPending
{
  if [[ -r "${KEMA_SAVED_CONFIG}" ]]; then
    return 0
  else
    return 1
  fi
}

# Ensure we have super-power
[[ ${UID} == 0 ]] || eerror $(eval_gettext "You must be super-user to run kema")

# Load bootloader functions
if [[ -z "${KEMA_BOOTLOADER}" ]]; then
  ewarn $(eval_gettext "No bootloader defined, using default one")
  . "${KEMA_BOOTLOADER_DIR}/default"
elif [[ -r "${KEMA_BOOTLOADER_DIR}/${KEMA_BOOTLOADER}" ]]; then
  . "${KEMA_BOOTLOADER_DIR}/${KEMA_BOOTLOADER}"
else
  eerror $(eval_gettext "Could not find \${KEMA_BOOTLOADER} bootloader file")
fi

# Which command was typed
if [[ -z ${1} ]]; then
  ehelp $(eval_gettext "No command given to kema")
elif [[ ${1} == "--help" ]]; then
  . "${KEMA_CORE_DIR}/kema-help"
elif [[ -r "${KEMA_CORE_DIR}/kema-${1}" ]]; then
  KEMA_COMMAND="kema-${1}"
  shift
  . "${KEMA_CORE_DIR}/${KEMA_COMMAND}" "$@"
elif [[ -r $(ls "${KEMA_CORE_DIR}/kema-${1}"* 2>/dev/null) ]]; then
  KEMA_COMMAND="kema-${1}"
  shift
  . "${KEMA_CORE_DIR}/${KEMA_COMMAND}"* "$@"
else
  BAD_COMMAND="${1}"
  ehelp $(eval_gettext "Unknown command: \${BAD_COMMAND}")
fi

